spring.application.name=votechain
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/votechain
spring.datasource.username=votechain
spring.datasource.password=votechain123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
jwt.secret=votechain-secret-key-sysec-2024-diego
jwt.expiration-ms=28800000

# Blockchain
blockchain.difficulty=4
blockchain.proof-char=0
